### ISSUE TITLE
Add code for Longest path problem

### ISSUE THREAD

**Issue by Thuva4** [Thuva4/Algorithms#60]

**Comment by vicennial** [comment]
Opened PR #95 for this issue.

**Comment by williamfiset** [comment]
Are we talking longest path on a Directed Acyclic Graph (DAG) or the general case? I can code up the one for the DAG case all you do is perform a topsort, negate all the edges, use DP to find the shortest path from A to B.

**Comment by Thuva4** [comment]
@williamfiset Both
