### ISSUE TITLE
Create the missing Algorithms in Java

### ISSUE THREAD

**Issue by Thuva4** [Thuva4/Algorithms#603]
Follow [CONTRIBUTING.md](https://github.com/Thuva4/Algorithms/blob/master/CONTRIBUTING.md)

**Comment by bermylle** [comment]
Hi first timer!

**Comment by ConnectNitish** [comment]
Hi I would like to work on this. Can you please assign me this.

**Comment by Thuva4** [comment]
@bermylle @ConnectNitish Thank you for your interest 👍 Please check the Java folder for missing algorithms.

**Comment by vyom153069** [comment]
i want to implement factorial using java , can you assign this to me?

**Comment by Thuva4** [comment]
@vyom153069 Please check the Java folder for missing algorithms.

**Comment by giatuongtran9** [comment]
Hi, I would like to work on this.
