### ISSUE TITLE
Create the missing Algorithms in Python

### ISSUE THREAD

**Issue by Thuva4** [Thuva4/Algorithms#604]
Follow [CONTRIBUTING.md](https://github.com/Thuva4/Algorithms/blob/master/CONTRIBUTING.md)

**Comment by BarnikRay** [comment]
I would like to work on this issue

**Comment by dkapur17** [comment]
I would like to work on this issue. TIA.

**Comment by kab11** [comment]
I would like to work on this issue.

**Comment by Thuva4** [comment]
@BarnikRay @dkapur17 @kab11 Thank you for your interest 👍 Please check the python folder for missing algorithms.

**Comment by daniccan** [comment]
https://github.com/Thuva4/Algorithms/pull/632 - Pearson Hashing in Python

**Comment by sumitjain0695** [comment]
I would like to add some algorithms in python.
