### ISSUE TITLE
Create the missing Algorithms in C

### ISSUE THREAD

**Issue by Thuva4** [Thuva4/Algorithms#605]
Follow [CONTRIBUTING.md](https://github.com/Thuva4/Algorithms/blob/master/CONTRIBUTING.md)

**Comment by sourabbr** [comment]
I would like to work on this. Can you name few algorithms you want.

**Comment by dkapur17** [comment]
I would like to work on this. TIA.

**Comment by sonali2105** [comment]
I would like to work on this.I would like to implement Insertion Sort Algorithms.Can you please assign this task to  me.

**Comment by Sidx-sys** [comment]
I would like to work on the implementation of the XOR swap,Please assign this task to me. TIA

**Comment by Thuva4** [comment]
@sourabbr @dkapur17 @sonali2105 Thank you for your interest 👍 Please check the C folder for missing algorithms.
