### ISSUE TITLE
Create the missing Algorithms in Rust

### ISSUE THREAD

**Issue by p-avital** [Thuva4/Algorithms#606]
Hello,
I'd like to work on some algorithms for hacktoberfest in Rust, was thinking mostly of fft, and probably a few others. Would you mind making a hacktoberfest tagged issue for Rust too ?
Thanks :)

**Comment by Thuva4** [comment]
Sure

**Comment by Thuva4** [comment]
Follow [CONTRIBUTING.md](https://github.com/Thuva4/Algorithms/blob/master/CONTRIBUTING.md)

**Comment by p-avital** [comment]
Done on all of my PRs, although you may want to use the generator from now on rather than the updated README.md in the requests.
