### ISSUE TITLE
Create the missing Algorithms in Swift

### ISSUE THREAD

**Issue by Thuva4** [Thuva4/Algorithms#609]
Follow [CONTRIBUTING.md](https://github.com/Thuva4/Algorithms/blob/master/CONTRIBUTING.md)

**Comment by Reza-Rajabi** [comment]
Hi,
I would like to work on the Merge Sort algorithm. Thank you.

**Comment by Thuva4** [comment]
@Reza-Rajabi Thank you for your interest :+1:  Please check the Swift folder for missing algorithms.

**Comment by Reza-Rajabi** [comment]
The  Insertion Sort was written by other developers, so I did the Edit Distance algorithm in Swift, and I have made a pull request. Thank you.
