### ISSUE TITLE
Create the missing Algorithms in Ruby

### ISSUE THREAD

**Issue by Thuva4** [Thuva4/Algorithms#612]
Follow [CONTRIBUTING.md](https://github.com/Thuva4/Algorithms/blob/master/CONTRIBUTING.md)

**Comment by zackster** [comment]
https://github.com/Thuva4/Algorithms/pull/613

**Comment by daniccan** [comment]
https://github.com/Thuva4/Algorithms/pull/633 - Xor Swap implementation in Ruby

**Comment by daniccan** [comment]
https://github.com/Thuva4/Algorithms/pull/634 - Linear Search implementation in Ruby

**Comment by daniccan** [comment]
https://github.com/Thuva4/Algorithms/pull/637 - Pearson Hashing in Ruby
