### ISSUE TITLE
Create the missing Algorithms in Kotlin

### ISSUE THREAD

**Issue by Thuva4** [Thuva4/Algorithms#615]
Follow [CONTRIBUTING.md](https://github.com/Thuva4/Algorithms/blob/master/CONTRIBUTING.md)

**Comment by Thuva4** [comment]
@ghiermann Thank you for your interest +1 Please check the Kotlin folder for missing algorithms.

**Comment by Kshitij09** [comment]
I'd like to add few algorithms in Kotlin. Should I make separate Pull request for each ?
