### ISSUE TITLE
Create the missing Algorithms in Perl

### ISSUE THREAD

**Issue by Thuva4** [Thuva4/Algorithms#617]
Follow [CONTRIBUTING.md](https://github.com/Thuva4/Algorithms/blob/master/CONTRIBUTING.md)

**Comment by jonasbn** [comment]
I have cleaned the two search implementations

**Comment by jonasbn** [comment]
I have corrected the bubble sort implementation (it was not correct)

**Comment by jonasbn** [comment]
I have added a simple recursive implementation of Fibonacci in Perl #760

**Comment by jonasbn** [comment]
I am pondering on how tests could be implemented.
