### ISSUE TITLE
Create the missing Algorithms in Rust

### ISSUE THREAD

**Issue by Thuva4** [Thuva4/Algorithms#618]
Follow [CONTRIBUTING.md](https://github.com/Thuva4/Algorithms/blob/master/CONTRIBUTING.md)

**Comment by ghiermann** [comment]
I would like to work on this too!
and there seem to be two issues for rust: https://github.com/Thuva4/Algorithms/issues/606

**Comment by Thuva4** [comment]
@ghiermann  Thank you for your interest +1 Please check the Rust folder for missing algorithms.
