### ISSUE TITLE
Case-insensitive fs collide all stuffs

### ISSUE THREAD

**Issue by vzsky** [Thuva4/Algorithms#661]
**Describe the bug**
Case-insensitive filesystems collide all stuffs that's named the same (Case-different)
which might cause real annoying probs in the future

**Rename all those things to something like *algo.x* and *algo_1.x* is better.**

**Comment by Thuva4** [comment]
Could you please list out the affected paths?

**Comment by vzsky** [comment]
Sure, 
in my case I found
```
  'BrainFuck/BubbleSort/BubbleSort.bf'
  'Brainfuck/BubbleSort/BubbleSort.bf'
  'BrainFuck/Fibonacci/Fibonacci.bf'
  'Brainfuck/Fibonacci/Fibonacci.bf'
  'C++/BellmanFord/BellmanFord.cpp'
  'C++/BellmanFord/bellmanford.cpp'
  'C++/BubbleSort/Bubble_Sort.cpp'
  'C++/BubbleSort/bubble_sort.cpp'
  'C++/XorSwap/XorSwap.cpp'
  'C++/XorSwap/xorswap.cpp'
  'C/Kadanes/Kadanes.c'
  'C/Kadanes/kadanes.c'
  'JavaScript/MergeSort/mergeSort.js'
  'JavaScript/MergeSort/mergesort.js'
```

**Comment by Thuva4** [comment]
Is it possible to fix them? If yes, Create a PR.

**Comment by cielavenir** [comment]
It seems https://github.com/Thuva4/Algorithms/commit/389568b4007d00a45438b5929231c6b19ae85d2a removed those files (the red-iconed ones).

**Comment by jonasbn** [comment]
This issue seems to have been fixed as stated by @cielavenir

**Comment by cielavenir** [comment]
@jonasbn no, we need to recommit those files with renamed

**Comment by jonasbn** [comment]
Made a new fork yesterday and did not observe the issue 😮

**Comment by jonasbn** [comment]
@cielavenir I will have a look

**Comment by jonasbn** [comment]
@cielavenir the mentioned paths seems to have been cleaned, so only a single implementation exist and not case variations of the same files.

Please let me know of you observe something else, I would be happy to make the required PRs.

**Comment by Thuva4** [comment]
Thank you, I will close this issue.
