### ISSUE TITLE
Add code for Breadth-first search

### ISSUE THREAD

**Issue by Thuva4** [Thuva4/Algorithms#72]

**Comment by srpurwaha201** [comment]
Can i implement it in c++?

**Comment by Thuva4** [comment]
Please read the contribution guide.

**Comment by tanya-vedi** [comment]
Can I implement this in Java?

**Comment by aadityadavera** [comment]
#167 Implementation in Python

**Comment by francisngo** [comment]
Can I implement this in JavaScript?

**Comment by francisngo** [comment]
Currently, there is no "thumbs-up" for Breadth First Search in JavaScript.

**Comment by Thuva4** [comment]
@francisngo Sorry, File is Already there. Can you update the Readme :+1:
