### ISSUE TITLE
Add code for Merge sort

### ISSUE THREAD

**Issue by Thuva4** [Thuva4/Algorithms#81]

**Comment by karthikmuralidharan** [comment]
Hi @Thuva4 , I can take it up.

**Comment by srpurwaha201** [comment]
Can i implement it in c++?

**Comment by Thuva4** [comment]
Please read the contribution guide.

**Comment by prateekpandey14** [comment]
Can i do this in GO ?

**Comment by tanya-vedi** [comment]
Can I implement this in Java?

**Comment by tanya-vedi** [comment]
#135

**Comment by adikul30** [comment]
Solution for C added #150

**Comment by Crowton** [comment]
Can I update the java version to use any type of object, aka generic objects, instead of only int?

**Comment by Thuva4** [comment]
@Crowton Yes , Submit as a another file.

**Comment by Crowton** [comment]
@Thuva4 okay; it has been uploaded now
