### ISSUE TITLE
Add code for Longest common subsequence problem

### ISSUE THREAD

**Issue by Thuva4** [Thuva4/Algorithms#86]

**Comment by Pritom14** [comment]
I would like to resolve the issue

**Comment by Thuva4** [comment]
Please read the contribution guide.

**Comment by Pritom14** [comment]
Thank you for allowing me to send a PR. I have read the contribution guide.

**Comment by Pritom14** [comment]
Please check #109

**Comment by sarthak-sopho** [comment]
Check #132 for C++ code

**Comment by aadityadavera** [comment]
#161 Implementation in Python

**Comment by aadityadavera** [comment]
#168 Implementation in Ruby
