### ISSUE TITLE
Issue while cloning repo

### ISSUE THREAD

**Issue by azhar1038** [Thuva4/Algorithms#885]
**Describe the bug**
[BloomFilterTest.py.](https://github.com/Thuva4/Algorithms/blob/master/algorithms/Python/BloomFilter/BloomFilterTest.py.) is causing following error while trying to clone repository:
```
error: invalid path 'algorithms/Python/BloomFilter/BloomFilterTest.py.'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

**To Reproduce**
Run the clone command:
```
$ git clone https://github.com/Thuva4/Algorithms.git
```

**Expected behavior**
It should clone the repo without problem

**Desktop (please complete the following information):**
 - OS: WIndows 10
 - Browser: Chrome
 - Version: Chrome Version 94.0.4606.61

**Additional context**
There is an extra period(.) at the end of file which is causing the issue

**Comment by azhar1038** [comment]
Currently to overcome this problem, one needs to set the following flag:
```
git config core.protectNTFS false
```

**Comment by Thuva4** [comment]
Removed file #888.
